export const links = [
    {
        name: 'New-Delhi',
        submenu: true,
        country: [
            {
                sublink: [
                    {name: "India", link: "/"}
                ],
            },
        ],
        nearbyCity: [
            {
                Head: "Nearby Cities",
                sublink: [
                    {name: "Gurgaon", link: "/"},
                    {name: "Greater Noida", link: "/"},
                    {name: "Ghaziabad", link: "/"},
                    {name: "Noida", link: "/"}
                ],
            },
        ],
        popularCity: [
            {
                Head: "Popular Cities",
                sublink: [
                    {name: "Ahmedabad", link:"/"},
                    {name: "Banglore", link:"/"},
                    {name: "Beyond Thane", link:"/"},
                    {name: "Chennai", link:"/"},
                    {name: "Gurgaon", link: "/"},
                    {name: "Hyderabad", link:"/"},
                    {name: "Indore", link:"/"},
                    {name: "Jaipur", link:"/"},
                    {name: "Kolkata", link:"/"},
                    {name: "Lucknow", link:"/"},
                    {name: "Mumbai", link:"/"},
                    {name: "Namvi Mumbai", link:"/"},
                    {name: "New Delhi", link:"/"},
                    {name: "Noida", link:"/"},
                    {name: "Pune", link:"/"},
                    {name: "Thane", link:"/"}
                ],
            },
            {
                Head: "Other Cities",
                sublink: [
                    {name: "Agra", link:"/"},
                    {name: "Ahmadanagar", link:"/"},
                    {name: "Allahabad", link:"/"},
                    {name: "Aluva", link:"/"},
                    {name: "Amritsar", link:"/"},
                    {name: "Aurangabad", link:"/"},
                    {name: "Badlapur", link:"/"},
                    {name: "Bareilly", link: "/"},
                    {name: "Belgaum", link:"/"},
                    {name: "Bhiwadi", link:"/"},
                    {name: "Bhiwandi", link:"/"},
                    {name: "Bhopal", link:"/"},
                    {name: "Bhubneswar", link:"/"},
                    {name: "Bokaro Steel City", link:"/"},
                    {name: "Chandigarh", link:"/"},
                    {name: "Chengalpattu", link:"/"},
                    {name: "Coimbatore",link:"/"},
                    {name: "Dehradun",link:"/"},
                    {name: "Durgapur",link:"/"},
                    {name: "Ernakulam",link:"/"},
                    {name: "Erode",link:"/"},
                    {name: "Faridabad",link:"/"},
                    {name: "Ghaziabad",link:"/"},
                    {name: "Goa",link:"/"},
                    {name: "Gorakhpur",link:"/"},
                    {name: "Greater Noida",link:"/"},
                    {name: "Guntur",link:"/"},
                    {name: "Guwahati",link:"/"},
                    {name: "Gwalior",link:"/"},
                    {name: "Haridwar",link:"/"},
                    {name: "Hosur",link:"/"},
                    {name: "Hubli",link:"/"},
                    {name: "Jabalpur",link:"/"},
                    {name: "Jalandhar",link:"/"},
                    {name: "Jammu",link:"/"},
                    {name: "Jamshedpur",link:"/"},
                    {name: "Jodhpur",link:"/"},
                    {name: "Kalyan",link:"/"},
                    {name: "Kannur",link:"/"},
                    {name: "Kanpur",link:"/"},
                    {name: "Khopoli",link:"/"},
                    {name: "Kochi",link:"/"},
                    {name: "Kodaikanal",link:"/"},
                    {name: "Kottayam",link:"/"},
                    {name: "kozhikode",link:"/"},
                    {name: "Lonavala",link:"/"},
                    {name: "Ludhiana",link:"/"},
                    {name: "Madurai",link:"/"},
                    {name: "Mangalore",link:"/"},
                    {name: "Mohali",link:"/"},
                    {name: "Mysore",link:"/"},
                    {name: "Nagpur",link:"/"},
                    {name: "Nainital",link:"/"},
                    {name: "Nanded",link:"/"},
                    {name: "Nashik",link:"/"},
                    {name: "Navsari",link:"/"},
                    {name: "Nellore",link:"/"},
                    {name: "Newtown",link:"/"},
                    {name: "Ooty",link:"/"},
                    {name: "Palakkad",link:"/"},
                    {name: "Palghar",link:"/"},
                    {name: "Punchkula",link:"/"},
                    {name: "Patiala",link:"/"},
                    {name: "Patna",link:"/"},
                    {name: "Pondicherry",link:"/"},
                    {name: "Raipur",link:"/"},
                    {name: "Rajahmundry",link:"/"},
                    {name: "Ranchi",link:"/"},
                    {name: "Salem",link:"/"},
                    {name: "Satara",link:"/"},
                    {name: "Shimla",link:"/"},
                    {name: "Siliguri",link:"/"},
                    {name: "Solapur",link:"/"},
                    {name: "Sonipat",link:"/"},
                    {name: "Surat",link:"/"},
                    {name: "Thanjavur",link:"/"},
                    {name: "Thrissur",link:"/"},
                    {name: "Tirunelveli",link:"/"},
                    {name: "Tirupati",link:"/"},
                    {name: "Tirupur",link:"/"},
                    {name: "Trichy",link:"/"},
                    {name: "Trivandrum",link:"/"},
                    {name: "Tumkur",link:"/"},
                    {name: "Udaipur",link:"/"},
                    {name: "Udupi",link:"/"},
                    {name: "Vadodara",link:"/"},
                    {name: "Vapi",link:"/"},
                    {name: "Varanasi",link:"/"},
                    {name: "Vijayawada",link:"/"},
                    {name: "Vishakhapatnam",link:"/"},
                    {name: "Vrindavan",link:"/"},
                    {name: "Zirakpur",link:"/"},
                ],
            },
        ],
    },
];